# Generated by Django 2.2 on 2019-12-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
